### PR TITLE
Fix a typo in README.md

### PR DESCRIPTION
**Pull request by rpherbig**

### CODE REVIEW

**Review by qaisjp-stripe — APPROVED** [review]

**Comment by rpherbig** [comment]
@qaisjp-stripe when I try to follow the `Contributor License Agreement` link, I get a nearly blank page (`Version` is not an element I can interact with):

chrome_vLC8HGE4GE

When I opened the Console and forced a number of elements to be visible, I can at least see the elements I would expect (`Sign In`, `I Accept`, etc.), but trying to submit anything gives me an error.

**Comment by qaisjp** [comment]
Hi @rpherbig - thank you so much for taking a look at this and filing https://github.com/cla-assistant/cla-assistant/issues/607 - I'll keep an eye on that issue!

**Comment by rpherbig** [comment]
> All committers have signed the CLA.

@qaisjp it looks like it's working now (I'll let them know in the issue too)

**Comment by qaisjp** [comment]
Thank you! I'll try to get this merged next week :)

**Comment by qaisjp** [comment]
It took a while but we got there eventually!

edit: lol, it looks like the typo was fixed a while ago. Thank you for the PR anyway!

**Pull request merged**
